---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[yum-atomic::default]
